### ISSUE TITLE
[Feature Request] Show some kind of graphical feedback for messages that fail to deliver

### ISSUE THREAD

**Issue by CSab6482** [open-imcore/imcore.react#28]
![Computer](https://user-images.githubusercontent.com/53708281/114648512-fb56a680-9cac-11eb-88f9-2e9ebb38d435.png)
![Phone](https://user-images.githubusercontent.com/53708281/114648515-fc87d380-9cac-11eb-8d24-ffde0f345284.png)

**Comment by CSab6482** [comment]
I honestly have no good way of testing this, so I'm going to assume that the

> Gracefully fail when the message description fails

from https://github.com/open-imcore/imessage-rest/actions/runs/761436416 means that this was fixed. Please reopen it if I'm incorrect

**Comment by EricRabil** [comment]
That doesn't fix this, sorry. I'll add a graphical indicator for when the message failed to send. I have no mechanism for re-trying a message right now, but I'll add that a later time.
